export EDITOR="code --wait --new-window"

alias b="bundle"
alias be="bundle exec"
alias e="$EDITOR"
alias hl="heroku local"

export LAPTOP="$HOME/laptop"

# Prepend laptop scripts
export PATH="$LAPTOP/bin:$PATH"
