export EDITOR="code . --wait --new-window"

alias b="bundle"
alias bd="bin/dev"
alias be="bundle exec"
alias by="bin/yarn"
alias e="code . --new-window"
alias gc="bin/rails generate component"
alias ih="bundle exec i18n-tasks health"
alias in="bundle exec i18n-tasks normalize"

# Homebrew
PATH="/opt/homebrew/bin:$PATH"

# Laptop
export LAPTOP="$HOME/laptop"
PATH="$LAPTOP/bin:$PATH"

# Postgres.app
PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"

# Color
autoload -U colors
colors
export CLICOLOR=1

# Prompt
function git_prompt_info() {
  current_branch=$(git current-branch 2> /dev/null)
  if [[ -n $current_branch ]]; then
    echo " %{$fg_bold[green]%}$current_branch%{$reset_color%}"
  fi
}
setopt promptsubst

if ! env | grep -q '^PS1='; then
  PS1='%{$fg_bold[blue]%}%c%{$reset_color%}$(git_prompt_info) %# '
fi

# Completion
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi
autoload -Uz compinit
compinit -u

source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

eval "$(mise activate zsh)"

export PATH
