export EDITOR="code --wait --new-window"

alias b="bundle"
alias be="bundle exec"
alias e="$EDITOR"
alias hl="heroku local"

export LAPTOP="$HOME/laptop"

# Prepend laptop scripts
export PATH="$LAPTOP/bin:$PATH"

# Prompt
function git_prompt_info() {
  current_branch=$(git current-branch 2> /dev/null)
  if [[ -n $current_branch ]]; then
    echo " %{$fg_bold[green]%}$current_branch%{$reset_color%}"
  fi
}
setopt promptsubst

if ! env | grep -q '^PS1='; then
  PS1='%{$fg_bold[blue]%}%c%{$reset_color%}$(git_prompt_info) %# '
fi
